DELETE http://localhost:3003/api/blogs/627575f30e9952bab9b1f655
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxvZ2ludGVzdHVzZXIiLCJpZCI6IjYyNzU2ZTRkOTA1YzRkZjcyYzE0YWRlYyIsImlhdCI6MTY1MTg2MzQ2OH0.J750-yTApJbqvZMMCHF9X7cz8RHdWUQ8C6QJ_fKI7D8